### ISSUE TITLE
Problem after reinstall system

### ISSUE THREAD

**Issue by rafalolb** [rawdlite/docker-mopidy#2]
I reinstall system and I get error if I want to playback local file:

```
New MPD connection from [::ffff:192.168.10.11]:56990
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Unknown error 524
```

My docker-compose file:
```
version: '3'
services:
  mopidy:
    image: rawdlite/mopidy
    container_name: mopidy
    devices:
      - "/dev/snd"
    ports:
      - "6600:6600"
      - "6680:6680"
    restart: unless-stopped
    volumes:
      - /home/rafal/mopidy/config/:/root/.config/
      - /home/rafal/mopidy/data/music/:/data/music/
```

What can I do?
